<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>OrderSystem.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OrderSystem.Application\OrderSystem.Application.csproj" />
    <ProjectReference Include="..\OrderSystem.Domain\OrderSystem.Domain.csproj" />
  </ItemGroup>
</Project>